services:
  mongodb:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
  frontend:
    build: .
    command: python -u run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    links:
      - mongodb
